# Generated by Django 2.2.13 on 2021-04-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leon', '0002_languagelearned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagelearned',
            old_name='id_language',
            new_name='language',
        ),
    ]
