# Generated by Django 2.2.13 on 2021-04-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leon', '0003_auto_20210424_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Language/img'),
        ),
    ]
