# Generated by Django 2.2.13 on 2021-04-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murillo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
