# Generated by Django 2.2.13 on 2021-04-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murillo', '0004_pokemon_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
