# Generated by Django 2.2.13 on 2021-04-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murillo', '0005_auto_20210409_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
