# Generated by Django 2.2.13 on 2021-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lozano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaisIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPais', models.IntegerField()),
                ('idLanguage', models.IntegerField()),
            ],
        ),
    ]
