# Generated by Django 3.1 on 2021-06-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarFacultad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default=None, max_length=2, null=True),
        ),
    ]
