# Generated by Django 2.2.13 on 2021-04-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
