# Generated by Django 2.2.13 on 2021-04-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='postura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
