# Generated by Django 3.1 on 2021-06-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarIndicadores', '0001_initial'),
        ('gestionarREAcreditadoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoacreditadora',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='REAcred_Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo')], default='1', max_length=2, null=True)),
                ('indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarIndicadores.indicador')),
                ('resultadoAcreditadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarREAcreditadoras.resultadoacreditadora')),
            ],
        ),
    ]
