# Generated by Django 3.1 on 2021-06-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarREAcreditadoras', '0002_auto_20210608_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoacreditadora',
            name='acreditadora',
        ),
        migrations.DeleteModel(
            name='REAcred_Indicador',
        ),
        migrations.DeleteModel(
            name='ResultadoAcreditadora',
        ),
    ]
