# Generated by Django 3.1 on 2021-05-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0002_auto_20210514_1738'),
        ('gestionarREAcreditadoras', '0002_auto_20210515_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoacreditadora',
            name='resultadoPUCP',
        ),
        migrations.AddField(
            model_name='resultadoacreditadora',
            name='resultadoPUCP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarResultados.resultadopucp'),
        ),
    ]
