# Generated by Django 3.1 on 2021-06-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0003_resultadopucp_especialidad'),
        ('gestionarREAcreditadoras', '0002_auto_20210608_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='REAcred_REPucp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('resultadoAcreditadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarREAcreditadoras.resultadoacreditadora')),
                ('resultadoPUCP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarResultados.resultadopucp')),
            ],
        ),
    ]
