# Generated by Django 3.1 on 2021-06-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarAcreditadoras', '0001_initial'),
        ('gestionarREAcreditadoras', '0004_auto_20210515_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoacreditadora',
            name='acreditadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarAcreditadoras.acreditadora'),
        ),
        migrations.DeleteModel(
            name='Acreditadora',
        ),
    ]
