# Generated by Django 3.1 on 2021-06-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarREAcreditadoras', '0004_resultadoacreditadora'),
        ('gestionarREAcreditadoras', '0003_reacred_repucp'),
    ]

    operations = [
    ]
