# Generated by Django 3.1 on 2021-06-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarREAcreditadoras', '0005_merge_20210608_2135'),
        ('gestionarREAcreditadoras', '0005_merge_20210608_2146'),
    ]

    operations = [
    ]
