# Generated by Django 3.1 on 2021-06-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarREAcreditadoras', '0005_merge_20210608_2106'),
        ('gestionarREAcreditadoras', '0006_merge_20210609_1015'),
    ]

    operations = [
    ]
