# Generated by Django 3.1 on 2021-06-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0004_auto_20210607_2301'),
        ('gestionarREAcreditadoras', '0007_merge_20210609_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoacreditadora',
            name='resultadoPUCP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarResultados.resultadopucp'),
        ),
    ]
