# Generated by Django 3.1 on 2021-06-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarIndicadores', '0001_initial'),
        ('gestionarREAcreditadoras', '0008_resultadoacreditadora_resultadopucp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoacreditadora',
            name='resultadoPUCP',
        ),
        migrations.AddField(
            model_name='resultadoacreditadora',
            name='indicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarIndicadores.indicador'),
        ),
    ]
