# Generated by Django 3.1 on 2021-07-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarREAcreditadoras', '0010_remove_resultadoacreditadora_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaREAcred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codIndicador', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('descpIndicador', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('resultadoAcreditadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarREAcreditadoras.resultadoacreditadora')),
            ],
        ),
    ]
