# Generated by Django 3.1 on 2021-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archive/'),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='evidencia',
            field=models.CharField(default=0, max_length=2, null=True),
        ),
    ]
