# Generated by Django 3.1 on 2021-06-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionarRubrica', '0001_initial'),
        ('gestionarSemestre', '0009_auto_20210531_2037'),
        ('gestionarCurso', '0004_delete_horario'),
        ('gestionarEvaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='rubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarRubrica.rubrica'),
        ),
        migrations.AddField(
            model_name='mediciondeindicador',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarEvaluacion.respuestaevaluacion'),
        ),
        migrations.AddField(
            model_name='mediciondeindicador',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarCurso.curso'),
        ),
        migrations.AddField(
            model_name='mediciondeindicador',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarSemestre.semestre'),
        ),
    ]
