# Generated by Django 3.1 on 2021-06-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarIndicadores', '0001_initial'),
        ('gestionarEvaluacion', '0002_auto_20210616_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarIndicadores.indicador'),
        ),
    ]
