# Generated by Django 3.1 on 2021-06-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0016_auto_20210623_1657'),
        ('gestionarEvaluacion', '0004_auto_20210623_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='planMedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarPlanMedicion.planmedicioncurso'),
        ),
    ]
