# Generated by Django 3.1 on 2021-06-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0006_alumno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='calificado',
            field=models.CharField(default=0, max_length=2, null=True),
        ),
    ]
