# Generated by Django 3.1 on 2021-06-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarHorario', '0005_delete_evidenciasxhorario'),
        ('gestionarEvaluacion', '0007_alumno_calificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarHorario.horario'),
        ),
    ]
