# Generated by Django 3.1 on 2021-06-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarRubrica', '0001_initial'),
        ('gestionarEvaluacion', '0008_auto_20210606_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='puntajeAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarRubrica.rubrica'),
        ),
    ]
