# Generated by Django 3.1 on 2021-06-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0009_alumno_puntajeasignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='puntajeAsignado',
            new_name='rubrica',
        ),
    ]
