# Generated by Django 3.1 on 2021-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0010_auto_20210606_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='rubrica',
        ),
        migrations.AddField(
            model_name='alumno',
            name='valorNota',
            field=models.IntegerField(null=True),
        ),
    ]
