# Generated by Django 3.1 on 2021-06-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0012_alumno_rubrica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediciondeindicador',
            name='alumno',
        ),
    ]
