# Generated by Django 3.1 on 2021-06-07 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarHorario', '0005_delete_evidenciasxhorario'),
        ('gestionarRubrica', '0001_initial'),
        ('gestionarEvaluacion', '0013_remove_mediciondeindicador_alumno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='RespuestaEvaluacion',
        ),
    ]
