# Generated by Django 3.1 on 2021-06-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvaluacion', '0014_auto_20210606_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediciondeindicador',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarEvaluacion.respuestaevaluacion'),
        ),
    ]
