# Generated by Django 3.1 on 2021-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarNivel', '0002_remove_nivel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='state',
            field=models.CharField(choices=[('0', 'Deleted'), ('1', 'Active')], default=None, max_length=2, null=True),
        ),
    ]
