# Generated by Django 3.1 on 2021-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarNivel', '0003_nivel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
