# Generated by Django 3.1 on 2021-06-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMejora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaactividadmejora',
            name='archivo',
            field=models.FileField(null=True, upload_to='mejora/'),
        ),
    ]
