# Generated by Django 3.1 on 2021-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMejora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadmejora',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
