# Generated by Django 3.1 on 2021-06-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0014_auto_20210617_1153'),
        ('gestionarPlanMejora', '0002_actividadmejora_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmejora',
            name='planMedicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarPlanMedicion.planmedicion'),
        ),
    ]
