# Generated by Django 3.1 on 2021-06-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionarResultados', '0002_auto_20210514_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('resultado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarResultados.resultadopucp')),
            ],
        ),
    ]
