# Generated by Django 3.1 on 2021-05-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarIndicadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='resultado_id',
            new_name='resultado',
        ),
    ]
