# Generated by Django 3.1 on 2021-06-08 01:02

from django.db import migrations, models
import gestionarAcreditadoras.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=gestionarAcreditadoras.models.upload_location)),
                ('estado', models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default=None, max_length=2, null=True)),
            ],
        ),
    ]
