# Generated by Django 3.1 on 2021-06-02 21:28

from django.db import migrations, models
import gestionarAcreditadoras.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarAcreditadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acreditadora',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=gestionarAcreditadoras.models.upload_location),
        ),
        migrations.AlterField(
            model_name='acreditadora',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
