# Generated by Django 2.2.13 on 2021-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
