# Generated by Django 2.2.13 on 2021-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
