# Generated by Django 2.2.13 on 2021-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pubgmteams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numPlayers', models.IntegerField(default=0)),
                ('region', models.CharField(max_length=100)),
                ('playedPMPLamericas', models.BooleanField(blank=True, default=False, null=True)),
                ('igl', models.CharField(blank=True, max_length=100, null=True)),
                ('scout', models.CharField(blank=True, max_length=100, null=True)),
                ('carry', models.CharField(blank=True, max_length=100, null=True)),
                ('support', models.CharField(blank=True, max_length=100, null=True)),
                ('sniper', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
