# Generated by Django 2.2.13 on 2021-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gilmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubgmteams',
            name='playedPMPLamericas',
        ),
    ]
