# Generated by Django 3.1 on 2021-06-09 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasxhorario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
