# Generated by Django 3.1 on 2021-06-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEvidencias', '0002_auto_20210606_1730'),
        ('gestionarEvidencias', '0002_auto_20210606_2111'),
    ]

    operations = [
    ]
