# Generated by Django 3.1 on 2021-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0002_auto_20210514_1738'),
        ('gestionarRE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoacreditadora',
            name='resultadoPUCP',
            field=models.ManyToManyField(to='gestionarResultados.ResultadoPUCP'),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
