# Generated by Django 3.1 on 2021-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarRE', '0002_resultadoacreditadora_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoacreditadora',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoacreditadora',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoacreditadora',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default='2', max_length=2, null=True),
        ),
    ]
