# Generated by Django 3.1 on 2021-06-02 21:28

from django.db import migrations, models
import django.db.models.deletion
import gestionarCurso.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('gestionarCurso', '0002_curso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to=gestionarCurso.models.upload_location)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarEspecialidad.especialidad')),
            ],
        ),
    ]
