# Generated by Django 3.1 on 2021-06-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarCurso', '0003_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
