# Generated by Django 3.1 on 2021-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='11111111', max_length=8),
        ),
    ]
