# Generated by Django 3.1 on 2021-06-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210513_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_actual',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
