# Generated by Django 3.1 on 2021-06-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_rol_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_rol',
            field=models.IntegerField(default=1),
        ),
    ]
