# Generated by Django 3.1 on 2021-06-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_count_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count_rol',
        ),
    ]
