# Generated by Django 3.1 on 2021-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_count_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='n_Roles',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
