# Generated by Django 3.1 on 2021-07-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestionarFacultad', '0001_initial'),
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('authentication', '0010_userxgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarEspecialidad.especialidad')),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarFacultad.facultad')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserxGroups',
        ),
        migrations.AddField(
            model_name='user',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user__set', related_query_name='user', through='authentication.UserGroups', to='auth.Group', verbose_name='groups'),
        ),
    ]
