# Generated by Django 3.1 on 2021-07-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('gestionarFacultad', '0001_initial'),
        ('authentication', '0012_auto_20210706_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Groups_Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGroup', models.IntegerField()),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarEspecialidad.especialidad')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarFacultad.facultad')),
            ],
        ),
        migrations.DeleteModel(
            name='UserxGroups',
        ),
    ]
