# Generated by Django 3.1 on 2021-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210706_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
    ]
