# Generated by Django 2.2.13 on 2021-04-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jhonatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='comida',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
