# Generated by Django 3.1 on 2021-05-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
