# Generated by Django 2.2.13 on 2021-04-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jherson', '0002_pokemon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
