# Generated by Django 2.2.13 on 2021-04-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jherson', '0003_tipo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
