# Generated by Django 2.2.13 on 2021-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jherson', '0004_auto_20210411_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='estado',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
