# Generated by Django 2.2.13 on 2021-04-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waffles',
            old_name='longitud',
            new_name='edad',
        ),
        migrations.RemoveField(
            model_name='waffles',
            name='habloElIdioma',
        ),
    ]
