# Generated by Django 2.2.13 on 2021-04-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaron', '0002_auto_20210404_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waffles',
            old_name='edad',
            new_name='precio',
        ),
    ]
