# Generated by Django 3.1 on 2021-06-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0016_auto_20210623_1657'),
        ('gestionarCurso', '0003_auto_20210621_1853'),
        ('gestionarHorario', '0003_auto_20210623_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='planCurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestionarPlanMedicion.planmedicioncurso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarCurso.curso'),
        ),
    ]
