# Generated by Django 3.1 on 2021-06-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0016_auto_20210623_1657'),
        ('gestionarHorario', '0004_auto_20210624_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='planCurso',
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarPlanMedicion.planmedicioncurso'),
        ),
    ]
