# Generated by Django 3.1 on 2021-06-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarHorario', '0004_auto_20210605_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvidenciasxHorario',
        ),
    ]
