# Generated by Django 2.2.13 on 2021-04-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('weapon', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
