# Generated by Django 3.1 on 2021-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarHorario', '0001_initial'),
        ('gestionarPlanMedicion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmedicion',
            name='horario',
            field=models.ManyToManyField(to='gestionarHorario.Horario'),
        ),
    ]
