# Generated by Django 3.1 on 2021-06-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0002_auto_20210615_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
