# Generated by Django 3.1 on 2021-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0006_auto_20210615_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmedicionhistorico',
            name='codigo',
            field=models.CharField(default='CODD01', max_length=10),
        ),
    ]
