# Generated by Django 3.1 on 2021-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0007_planmedicionhistorico_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmedicion',
            name='codigo',
            field=models.CharField(default='CODD01', max_length=10),
        ),
    ]
