# Generated by Django 3.1 on 2021-06-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0008_planmedicion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicion',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
