# Generated by Django 3.1 on 2021-06-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0010_auto_20210615_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicioncurso',
            name='planMedicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestionarPlanMedicion.planmedicionhistorico'),
        ),
    ]
