# Generated by Django 3.1 on 2021-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0012_auto_20210615_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanMedicionHistorico',
        ),
    ]
