# Generated by Django 3.1 on 2021-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarPlanMedicion', '0013_delete_planmedicionhistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicion',
            name='estado',
            field=models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Terminado')], default=None, max_length=2, null=True),
        ),
    ]
