# Generated by Django 3.1 on 2021-06-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0007_delete_semestreplan'),
        ('gestionarPlanMedicion', '0015_auto_20210623_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmedicion',
            name='planResultados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarResultados.planresultados'),
        ),
    ]
