# Generated by Django 3.1 on 2021-06-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarNiveles', '0002_auto_20210609_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='campo',
            field=models.IntegerField(default=None),
        ),
    ]
