# Generated by Django 3.1 on 2021-06-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarNiveles', '0003_nivel_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='campo',
        ),
    ]
