# Generated by Django 3.1 on 2021-07-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0008_auto_20210624_0054'),
        ('gestionarNiveles', '0004_remove_nivel_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='plaResultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarResultados.planresultados'),
        ),
    ]
