# Generated by Django 3.1 on 2021-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCodigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('anho', models.IntegerField(null=True)),
                ('etapa', models.IntegerField(null=True)),
                ('inicio', models.CharField(max_length=20, null=True)),
                ('fin', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
