# Generated by Django 3.1 on 2021-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
