# Generated by Django 3.1 on 2021-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0003_auto_20210510_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
