# Generated by Django 3.1 on 2021-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0004_auto_20210510_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='fin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='inicio',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
