# Generated by Django 3.1 on 2021-05-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0005_auto_20210511_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='etapa',
            field=models.IntegerField(null=True),
        ),
    ]
