# Generated by Django 3.1 on 2021-05-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0006_auto_20210511_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='anho',
            field=models.IntegerField(null=True),
        ),
    ]
