# Generated by Django 3.1 on 2021-06-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0007_auto_20210511_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nombreCodigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
