# Generated by Django 3.1 on 2021-06-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0008_auto_20210531_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nombreCodigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
