# Generated by Django 3.1 on 2021-05-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarFacultad', '0001_initial'),
        ('gestionarEspecialidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='facultad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionarFacultad.facultad'),
        ),
    ]
