# Generated by Django 3.1 on 2021-05-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='inicio',
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
