# Generated by Django 3.1 on 2021-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0003_asistente_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='versiones',
            field=models.IntegerField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
