# Generated by Django 3.1 on 2021-05-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopucp',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
