# Generated by Django 3.1 on 2021-06-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('gestionarResultados', '0002_auto_20210514_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadopucp',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionarEspecialidad.especialidad'),
        ),
    ]
