# Generated by Django 3.1 on 2021-06-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('gestionarSemestre', '0001_initial'),
        ('gestionarResultados', '0004_auto_20210607_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanResultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('estado', models.CharField(blank=True, choices=[('0', 'Eliminado'), ('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarEspecialidad.especialidad')),
                ('resultados', models.ManyToManyField(to='gestionarResultados.ResultadoPUCP')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarSemestre.semestre')),
            ],
        ),
    ]
