# Generated by Django 3.1 on 2021-06-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarSemestre', '0001_initial'),
        ('gestionarEspecialidad', '0002_especialidad_estado'),
        ('gestionarResultados', '0005_planresultados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planresultados',
            name='semestre',
        ),
        migrations.CreateModel(
            name='SemestrePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarEspecialidad.especialidad')),
                ('planResultado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarResultados.planresultados')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionarSemestre.semestre')),
            ],
        ),
    ]
