# Generated by Django 3.1 on 2021-06-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0006_auto_20210616_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemestrePlan',
        ),
    ]
