# Generated by Django 3.1 on 2021-06-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarResultados', '0007_delete_semestreplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planresultados',
            name='resultados',
        ),
        migrations.RemoveField(
            model_name='resultadopucp',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='resultadopucp',
            name='planResultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionarResultados.planresultados'),
        ),
    ]
